### ISSUE TITLE
Show POI labels earlier (but not all landuse labels earlier)

### ISSUE THREAD

**Issue by nvkelso** [nvkelso/tangram-skin-and-bones#5]
Updated the POI labels demo should update Skin & Bones, too.

YAML syntax below. Looks to see if the area is not present: if it's not only start showing them at zoom 12. For the landuse label that have area, throttle the area per zoom. This allows the polygon to show earlier than the label (the polygons needs to be substantial on screen before it's label is shown).

```
poi_and_landuse_labels:
    data: { source: osm, layer: [pois, landuse_labels] }
    filter: 
        name: true
        not: { kind: [farm, peak, tree, gate] }
        any:
            - area: false
              all:
                  - $zoom: { min: 12 }
            - area: true
              any:
                  # show labels for smaller landuse areas at higher zooms
                  - { $zoom: { min: 9 },  area: { min: 100000000 } }
                  - { $zoom: { min: 10 }, area: { min: 100000000 } }
                  - { $zoom: { min: 11 }, area: { min: 25000000 } }
                  - { $zoom: { min: 12 }, area: { min: 5000000 } }
                  - { $zoom: { min: 13 }, area: { min: 2000000 } }
                  - { $zoom: { min: 14 }, area: { min: 500000 } }
                  - { $zoom: { min: 15 }, area: { min: 100000 } }
                  - { $zoom: { min: 15 }, area: { min: 50000 } }
                  - { $zoom: { min: 16 }, area: { min: 20000 } }
                  - { $zoom: { min: 18 } }
```
